// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ClickOutside: typeof import('@ly-js/ui/es')['ClickOutside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    LyEButton: typeof import('@ly-js/element/es')['Button']
    LyEForm: typeof import('@ly-js/element/es')['Form']
    LyEFormDialog: typeof import('@ly-js/element/es')['FormDialog']
    LyEFormItem: typeof import('@ly-js/element/es')['FormItem']
    LyEPage: typeof import('@ly-js/element/es')['Page']
    LyESelect: typeof import('@ly-js/element/es')['Select']
    LyETable: typeof import('@ly-js/element/es')['Table']
    LyETableColumn: typeof import('@ly-js/element/es')['TableColumn']
    LyETableLayout: typeof import('@ly-js/element/es')['TableLayout']
    LyEUpload: typeof import('@ly-js/element/es')['Upload']
    LyIcon: typeof import('@ly-js/ui/es')['Icon']
    LyScroll: typeof import('@ly-js/scroll/es')['Scroll']
    LyVFixedContainer: typeof import('@ly-js/vant/es')['FixedContainer']
    LyVPage: typeof import('@ly-js/vant/es')['Page']
    ScrollBar: typeof import('./src/components/ScrollBar.vue')['default']
    Src: typeof import('./src/components/scroll/src/index.vue')['default']
  }
}

export { }
